-------------------------------------------------------------------------------
Test set: TestSuite
-------------------------------------------------------------------------------
Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 1.881 s <<< FAILURE! - in TestSuite
loginTrue(com.test.jenkins.cases.LoginTest)  Time elapsed: 0.695 s  <<< FAILURE!
org.apache.http.conn.HttpHostConnectException: Connection to http://localhost:8889 refused
	at com.test.jenkins.cases.LoginTest.getResult(LoginTest.java:75)
	at com.test.jenkins.cases.LoginTest.loginTrue(LoginTest.java:42)
Caused by: java.net.ConnectException: Connection refused
	at com.test.jenkins.cases.LoginTest.getResult(LoginTest.java:75)
	at com.test.jenkins.cases.LoginTest.loginTrue(LoginTest.java:42)

loginFalse(com.test.jenkins.cases.LoginTest)  Time elapsed: 0.035 s  <<< FAILURE!
org.apache.http.conn.HttpHostConnectException: Connection to http://localhost:8889 refused
	at com.test.jenkins.cases.LoginTest.getResult(LoginTest.java:75)
	at com.test.jenkins.cases.LoginTest.loginFalse(LoginTest.java:56)
Caused by: java.net.ConnectException: Connection refused
	at com.test.jenkins.cases.LoginTest.getResult(LoginTest.java:75)
	at com.test.jenkins.cases.LoginTest.loginFalse(LoginTest.java:56)

